import org.specs._

object IncTest extends SpecBase {
  val module = new scalaxb.compiler.xsd2.Driver // with Verbose
  // val module = new scalaxb.compiler.xsd.Driver // with Verbose

  lazy val generated = module.processString(schemaString, "general")
  lazy val entitySource = generated(0)

  "the generated entity source" should {
    "starts with // Generated by" >> {
      entitySource must startWith("// Generated by")
    }

    "includes case class Address" >> {
      entitySource must include("case class Address")
    }

  }

}
