import org.specs._
import java.io.{File}
import scalaxb.compiler.{Config, Verbose}

object IncTest extends TestBase {
  val module = new scalaxb.compiler.xsd2.Driver // with Verbose
  lazy val generated = module.processString(schemaString, "general")
  lazy val entitySource = generated(0)

  "the generated entity source" should {
    "start with // Generated by" >> {
      entitySource must startWith("// Generated by")
    }

  }

}
